# Generated by Django 6.1.1 on 2026-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_request_replay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayrequest',
            name='body_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
